# Generated by Django 2.1.5 on 2019-02-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=35)),
                ('sexe', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_visite', models.DateField(null=True)),
                ('heure_darrivee', models.DateTimeField(null=True)),
                ('heure_depart', models.DateTimeField(null=True)),
                ('motif', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_registre.Personne')),
            ],
            bases=('e_registre.personne',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_registre.Personne')),
            ],
            bases=('e_registre.personne',),
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_registre.Personne')),
            ],
            bases=('e_registre.personne',),
        ),
        migrations.AddField(
            model_name='visite',
            name='personne',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_registre.Personne'),
        ),
    ]
